### ISSUE TITLE
Some tests methods fail randomly

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/PolyMath#104] opened 2019-04-30 12:43 UTC
Some tests methods like :
- ``PMKolmogorovSmirnov1SampleTest >> testRejectOfEqualityHypothesesForSampleVersusDistribution``
- ``PMBinomialGeneratorTest >> testBinomialGeneratorConvergesToMean``
fail randomly from time to time. 

They should be rewritten in a better way.
Maybe we should control the seed in order to have reproducible test.

**Comment by hemalvarambhia** [comment] 2019-04-30 20:38
This is a duplicate of #70, so I'll close that and this will be the new milestone issue.

**Comment by hemalvarambhia** [comment] 2019-04-30 20:58
I'm proposing we do something like `Random seed: 0` as it's probably as good as any.

**Comment by hemalvarambhia** [comment] 2019-05-11 12:49
@SergeStinckwich In the case of the K-S test work in PR #111 one observation I made is that the one talks about about retaining or rejecting the *null hypothesis*, whereas the message `rejectEqualityHypothesisWithAlpha` doesn't use that language. This is also the case in [wikipedia](https://en.wikipedia.org/wiki/Kolmogorov%E2%80%93Smirnov_test). So I was going to propose that we deprecate that in favour of `retainNullHypothesisWithin:` in a future version. What are your thoughts?

**Closed** 2019-05-13 09:53 UTC
Labels: Priority: Medium, Status: In Progress, Type: Bug
